export const ADD_FOOD = "ADD_FOOD";
export const EDIT_FOOD = "EDIT_FOOD";
export const DELETE_FOOD = "DELETE_FOOD";
export const GET_ALL_FOODS = "GET_ALL_FOODS";

export const ADD_CONSUMATION = "ADD_CONSUMATION";
export const EDIT_CONSUMATION = "EDIT_CONSUMATION";
export const DELETE_CONSUMATION = "DELETE_CONSUMATION";
export const GET_ALL_CONSUMATIONS = "GET_ALL_CONSUMATIONS";